_BASE_: "RSICD.yaml"
OUTPUT_DIR: './work_dirs/baseline_with_swin_end2end_V23_RL'
###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 8

######################################### Engine #########################################
ENGINE:
#  NAME: 'RLBeamTrainer'
#  NAME: 'RLMeanTrainer'
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '/data1/wlx/project/2022xmodaler/work_dirs/baseline_with_swin_end2end_V23/model_Epoch_00024_Iter_0021239.pth'
  USE_EMA: True
  EMA_DECAY: 0.9999

  BERT:
    HIDDEN_DROPOUT_PROB: 0.1
    INTERMEDIATE_DROP: 0.1
    FFN_DROPOUT_PROB: 0.1
    ATTENTION_PROBS_DROPOUT_PROB: 0.1
    LAYER_DROP: 0.0

####################################### losses ####################################### 
LOSSES:
  NAMES: ['LabelSmoothing']
  LABELSMOOTHING: 0.1

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 10
  BASE_LR: 0.00001

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  #NAME: 'FixLR'
  NAME: 'StepLR'
  STEP_SIZE: 3
  GAMMA: 0.8
